// Code generated by "stringer -type=JsonValueAnyUnderlyingType -output json_types_json_value_any_underlying_type_strings.go"; DO NOT EDIT.

package values

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JsonValueAnyUnderlyingTypeObject-0]
	_ = x[JsonValueAnyUnderlyingTypeNumber-1]
}

const _JsonValueAnyUnderlyingType_name = "JsonValueAnyUnderlyingTypeObjectJsonValueAnyUnderlyingTypeNumber"

var _JsonValueAnyUnderlyingType_index = [...]uint8{0, 32, 64}

func (i JsonValueAnyUnderlyingType) String() string {
	if i < 0 || i >= JsonValueAnyUnderlyingType(len(_JsonValueAnyUnderlyingType_index)-1) {
		return "JsonValueAnyUnderlyingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JsonValueAnyUnderlyingType_name[_JsonValueAnyUnderlyingType_index[i]:_JsonValueAnyUnderlyingType_index[i+1]]
}
