// Code generated by "stringer -type=tokenType -output tokentype_string_test.go"; DO NOT EDIT.

package gojason

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[invalidoTokenType-0]
	_ = x[jsonNumberTokenType-1]
	_ = x[jsonWhitespaceTokenType-2]
	_ = x[jsonColonTokenType-3]
	_ = x[jsonCurlyOpenBracketTokenType-4]
	_ = x[jsonCurlyClosingBracketTokenType-5]
	_ = x[jsonCommaTokenType-6]
}

const _tokenType_name = "invalidoTokenTypejsonNumberTokenTypejsonWhitespaceTokenTypejsonColonTokenTypejsonCurlyOpenBracketTokenTypejsonCurlyClosingBracketTokenTypejsonCommaTokenType"

var _tokenType_index = [...]uint8{0, 17, 36, 59, 77, 106, 138, 156}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
