// Code generated by "stringer -type=parseJsonObjectState -output parse_json_object_state_string.go"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PJOWaitingForKey-0]
	_ = x[PJOGotKeyWaitingForSeparator-1]
	_ = x[PJOGotKeyAndSeparatorWaitingForValue-2]
	_ = x[PJOGotValueWaitingForCommaOrEnd-3]
	_ = x[PJOWaitingForKeyAfterComma-4]
}

const _parseJsonObjectState_name = "PJOWaitingForKeyPJOGotKeyWaitingForSeparatorPJOGotKeyAndSeparatorWaitingForValuePJOGotValueWaitingForCommaOrEndPJOWaitingForKeyAfterComma"

var _parseJsonObjectState_index = [...]uint8{0, 16, 44, 80, 111, 137}

func (i parseJsonObjectState) String() string {
	if i < 0 || i >= parseJsonObjectState(len(_parseJsonObjectState_index)-1) {
		return "parseJsonObjectState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _parseJsonObjectState_name[_parseJsonObjectState_index[i]:_parseJsonObjectState_index[i+1]]
}
